---
ufw:
  state: enabled
  default_policy: deny
  rules:
  - port: "80"
    proto: tcp
    name: http
    rule: allow
  - port: "443"
    proto: tcp
    name: https
    rule: allow
  - port: ssh
    proto: tcp
    name: ssh
    rule: allow
  - port: "6443"
    proto: tcp
    name: k3s-api
    rule: allow
  - port: "30000:32767"
    proto: tcp
    name: k3s-nodeport-range
    rule: allow
  - port: "30000:32767"
    proto: udp
    name: k3s-nodeport-range-udp
    rule: allow
  - port: "8472"
    proto: udp
    name: k3s-flannel-vxlan
    rule: allow
  - port: "8472"
    proto: tcp
    name: k3s-flannel-health
    rule: allow
