---
- name: Configure UFW rules
  become: true
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: "{{ ufw.rules }}"
  loop_control:
    label: "{{ item.name }} ({{ item.port }}/{{ item.proto }})"

- name: Enable UFW
  become: true
  ufw:
    state: "{{ ufw.state }}"
    policy: "{{ ufw.default_policy }}"
