# Namespace-specific ingress routes and middlewares
%{ if namespace == "homelab" ~}
ingressRoutes:
  homepage:
    match: Host("home.kieranajp.uk")
    middlewares:
    - google-auth
    service:
      name: homepage
      port: 10352

  homeassistant:
    match: Host("homeassistant.kieranajp.uk")
    service:
      name: home-assistant
      port: 8080

  # Example API route using OAuth authentication for MCP
  api-example:
    match: Host("api.kieranajp.uk")
    middlewares:
    - oauth-auth
    service:
      name: api-service
      port: 8080
%{ endif ~}

%{ if namespace == "auth" ~}
ingressRoutes:
  # Hydra OAuth 2.0 public endpoints (token, authorize, well-known)
  hydra-public:
    match: Host("hydra.kieranajp.uk")
    service:
      name: hydra-public
      port: 4444

  # Hydra admin endpoints (protected with Google auth)
  hydra-admin:
    match: Host("hydra-admin.kieranajp.uk")
    middlewares:
    - google-auth
    service:
      name: hydra-admin
      port: 4445
%{ endif ~}

middlewares:
  google-auth:
    spec: |
      plugin:
        google-oidc-auth-middleware:
          oidc:
            clientID: "${google_client_id}"
            clientSecret: "${google_client_secret}"
          cookie:
            secret: "${cookie_secret}"
          authorized:
            domains:
            - kieranajp.co.uk

  oauth-auth:
    spec: |
      forwardAuth:
        address: "http://oathkeeper-proxy.auth.svc.cluster.local:4455"
        authResponseHeaders:
        - "X-User"