ingressRoutes:
  homepage:
    namespace: homelab
    match: Host("seldon.local") || Host("home.kieranajp.uk")
    middlewares:
    - google-auth
    service:
      name: homepage
      port: 10352

  home-assistant:
    namespace: homelab
    match: Host("homeassistant.seldon.local") || Host("homeassistant.kieranajp.uk")
    service:
      name: home-assistant
      port: 8080

middlewares:
  google-auth:
    namespace: homelab
    spec: |
      plugin:
        google-oidc-auth-middleware:
          oidc:
            clientID: "${google_client_id}"
            clientSecret: "${google_client_secret}"
          cookie:
            secret: "${cookie_secret}"
          authorized:
            domains:
            - kieranajp.co.uk
