{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
  routes:
  - match: {{ .Values.ingress.match | quote }}
    kind: Rule
    services:
    - name: {{ .Release.Name }}
      port: {{ .Values.service.port | default 8080 }}
{{- end }}
