apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.port | default 8080 }}
    targetPort: {{ .Values.service.port | default 8080 }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}
