---
- name: Get hostname
  shell: hostname
  register: hostname

- name: Uninstall k3s (if requested)
  shell: |
    /usr/local/bin/k3s-uninstall.sh
  when: reinstall_k3s is defined and reinstall_k3s
  ignore_errors: yes

- name: Wait for k3s uninstall to complete
  wait_for:
    path: /usr/local/bin/k3s
    state: absent
    timeout: 60
  when: reinstall_k3s is defined and reinstall_k3s

- name: Install k3s
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--tls-san={{ hostname.stdout }}.local" sh -
  args:
    creates: /usr/local/bin/k3s

- name: Ensure k3s is running
  systemd:
    name: k3s
    state: started
    enabled: yes
    daemon_reload: yes

- name: Wait for k3s config file to exist
  stat:
    path: /etc/rancher/k3s/k3s.yaml
  register: k3s_config
  until: k3s_config.stat.exists
  retries: 10
  delay: 5

- name: Wait for k3s to be responsive
  shell: timeout 10 kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml get nodes
  register: k3s_nodes
  until: k3s_nodes.rc == 0
  retries: 30
  delay: 10
  changed_when: false

- name: Create local kubeconfig directory
  file:
    path: "~/.kube"
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: Read k3s config content
  slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: k3s_config_content

- name: Write k3s config locally
  copy:
    content: "{{ k3s_config_content.content | b64decode }}"
    dest: "./k3s-config"
    mode: '0600'
  delegate_to: localhost

- name: Change ownership of k3s config
  file:
    path: "./k3s-config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  delegate_to: localhost

- name: Update kubeconfig server URL
  replace:
    path: "./k3s-config"
    regexp: 'https://127.0.0.1:6443'
    replace: 'https://{{ hostname.stdout }}.local:6443'
  delegate_to: localhost

- name: Update kubeconfig server name
  replace:
    path: "./k3s-config"
    regexp: 'default'
    replace: '{{ hostname.stdout }}'
  delegate_to: localhost

- name: Deploy Traefik configuration
  template:
    src: traefik-config.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
    owner: root
    group: root
    mode: '0644'
  notify: restart k3s
