---
- name: Ensure AUR packages are installed
  pacman:
    name: "{{ aur_packages }}"
    state: present
    update_cache: yes

- name: Create update script
  copy:
    content: |
      #!/bin/bash
      # Run system updates
      yay -Syu --noconfirm

      # Check if kernel was updated
      RUNNING_KERNEL=$(uname -r)
      INSTALLED_KERNEL=$(pacman -Q linux | awk '{print $2}')

      if [[ "$RUNNING_KERNEL" != "$INSTALLED_KERNEL" ]]; then
          echo "Kernel updated from $RUNNING_KERNEL to $INSTALLED_KERNEL"
          echo "Rebooting in 60 seconds to apply kernel update..."
          sleep 60
          reboot
      else
          echo "No kernel update, no reboot needed"
      fi
    dest: /usr/local/bin/auto-update
    mode: '0755'

- name: Create systemd timer
  copy:
    content: |
      [Unit]
      Description=Automatic system updates

      [Timer]
      OnCalendar=*-*-* {{ update_hour }}:{{ update_minute }}:00
      RandomizedDelaySec=300

      [Install]
      WantedBy=timers.target
    dest: /etc/systemd/system/auto-update.timer
    mode: '0644'

- name: Create systemd service
  copy:
    content: |
      [Unit]
      Description=Automatic system updates

      [Service]
      Type=oneshot
      ExecStart=/usr/local/bin/auto-update
    dest: /etc/systemd/system/auto-update.service
    mode: '0644'

- name: Enable and start update timer
  systemd:
    name: auto-update.timer
    enabled: yes
    state: started
    daemon_reload: yes
