{{- range $name, $route := .Values.ingressRoutes }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $name }}
  namespace: {{ $route.namespace }}
spec:
  entryPoints:
    - web
  routes:
  - match: {{ $route.match | quote }}
    kind: Rule
    services:
    - name: {{ $route.service.name }}
      port: {{ $route.service.port }}
{{- end }}
